---
# This role adds a new IP address to the RFS conf file

- name: Add client ips to hsms
  ansible.builtin.include_tasks: rfs_register_client.yaml
  loop: "{{ nshield_hsms }}"

- name: Allow bootstrap server to update the RFS server
  ansible.builtin.command: "/opt/nfast/bin/rfs-setup --gang-client --write-noauth  {{ thales_bootstrap_client_ip }}"
