---
- name: Legacy vars warning
  ansible.builtin.debug:
    msg: "WARNING: Using legacy thales_hsm_ip_address and
         thales_client_tarball_location variables.  Please udpate your
         vars file."
